### ISSUE TITLE
AttributeError: 'dict' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by sainimohit23** [ahmadfaizalbh/Chatbot#9]
**Describe the bug**
After importing demo from chatbot as shown in demo. When I run the function `demo()`. I get this:

``` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Babban\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\chatbot\__init__.py", line 827, in demo
    Chat().converse(firstQuestion)
  File "C:\Users\Babban\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\chatbot\__init__.py", line 103, in __init__
    elif 'unicode' in __builtins__.__dict__ and type(pairs) == __builtins__.__dict__['unicode']:
AttributeError: 'dict' object has no attribute '__dict__'
```

![screenshot_49](https://user-images.githubusercontent.com/26195811/53097982-aabde580-3548-11e9-8dcd-82c65e13eefc.png)

**Comment by ahmadfaizalbh** [comment]
Fixed [commit](https://github.com/ahmadfaizalbh/Chatbot/commit/5f886076f5116092226f61fc80264faa345b9839)

**Comment by ahmadfaizalbh** [comment]
Fixed
